#ifndef __FRONT_DEFINE_H__
#define __FRONT_DEFINE_H__

enum ServerModule
{
    SERVER_MODULE_CACHE_SERVER = 0,
	SERVER_MODULE_LOBBY_SERVER,
	SERVER_MODULE_GAME_SERVER,
    SERVER_MODULE_CHATTING_SERVER,
	SERVER_MODULE_CLIENT,

	SERVER_MODULE_COUNT
};

#endif //__FRONT_DEFINE_H__


