#pragma once

#define SCREEN_WIDTH 1280
#define SCREEN_HEIGHT 720

#define TILE_WIDTH_SIZE 128
#define TILE_HEIGHT_SIZE 64

#define TILE_WIDTH_NUM 100
#define TILE_HEIGHT_NUM 100

#define NETWORK_FPS 6

#define PLAY_ALONE 0
#define DIVIDE_NODE 1