
#ifndef __GAME_DEFINES_H__
#define __GAME_DEFINES_H__


enum LAYER_TAG
{
	TAG_NETWORK_LAYER = 1,
	TAG_LOGIN_SCENE,
	TAG_SIGN_UP_LAYER,
	TAG_FRONT_SCENE,
	TAG_LOBBY_SCENE,
    TAG_RESULT_SCENE,
    TAG_ROOM_SCENE,
	TAG_GAME_SCENE,
	TAG_POP_UP,
	TAG_MENU,
	TAG_CHANNEL_LIST_LAYER,
	TAG_USER_LIST_LAYER,
	TAG_USER_INFO_LAYER,
	TAG_ROOM_LIST_LAYER,
	TAG_MAKE_ROOM_LAYER,
	TAG_REQUEST_LIST_LAYER,
	TAG_SELETION_LAYER,
	TAG_FIND_ROOM_LAYER,
	TAG_QUICK_PLAY_LAYER,

};

enum CurrentScene
{
	LOGIN_SCENE_NOW = 1,
	FRONT_SCENE_NOW,
	LOBBY_SCENE_NOW,
    ROOM_SCENE_NOW,
	GAME_SCENE_NOW,
    RESULT_SCENE_NOW,
};



#endif //__GAME_DEFINES_H__
