
#ifndef __GAME_DEFINES_H__
#define __GAME_DEFINES_H__

#define DISPLAY_WIDTH 720
#define DISPLAY_HEIGHT 1280

#define MENU_BUTTON_LAYER_Y 0
#define MENU_BUTTON_LAYER_HEIGHT 120
#define MY_INFO_LAYER_Y (DISPLAY_HEIGHT - 150)
#define MY_INFO_LAYER_HEIGHT 150
#define LOBBY_LAYER_Y MENU_BUTTON_LAYER_HEIGHT
#define LOBBY_LAYER_HEIGHT (DISPLAY_HEIGHT - MY_INFO_LAYER_HEIGHT - MENU_BUTTON_LAYER_HEIGHT)


enum LAYER_TAG
{
	TAG_NETWORK_LAYER = 1,
    TAG_HELLO_WORLD_SCENE,
	TAG_LOGIN_SCENE,
    TAG_CREATE_ACCOUNT_LAYER,
	TAG_SIGN_UP_LAYER,
	TAG_FRONT_SCENE, //
	TAG_LOBBY_SCENE,
    TAG_MENU_BUTTON_LAYER,
    TAG_MY_INFO_LAYER,
    TAG_LOBBY_GAME_LAYER,
    TAG_LOBBY_CHANNEL_LAYER,
    TAG_LOBBY_FRIEND_LAYER,
    TAG_LOBBY_CLAN_LAYER,
    TAG_LOBBY_RANKING_LAYER,
    TAG_LOBBY_BOARD_LAYER,
    
    
    
    
    TAG_RESULT_SCENE,
    TAG_ROOM_SCENE,
	TAG_GAME_SCENE,
	TAG_POP_UP,
	TAG_MENU,
	TAG_CHANNEL_LIST_LAYER,
	TAG_USER_LIST_LAYER,
	TAG_USER_INFO_LAYER,
	TAG_ROOM_LIST_LAYER,
	TAG_MAKE_ROOM_LAYER,
	TAG_REQUEST_LIST_LAYER,
	TAG_SELETION_LAYER,
	TAG_FIND_ROOM_LAYER,
	TAG_QUICK_PLAY_LAYER,
    
};

enum CurrentScene
{
	HELLO_WORLD_SCENE_NOW = 1,
	LOGIN_SCENE_NOW,
	LOBBY_SCENE_NOW,
    ROOM_SCENE_NOW,
	GAME_SCENE_NOW,
    RESULT_SCENE_NOW,
    NO_SCENE_NOW,
};



#endif //__GAME_DEFINES_H__
